package com.github.catchitcozucan.core.demo.trip;

import com.github.catchitcozucan.core.ProcessBpmSchemeRepo;
import com.github.catchitcozucan.core.ProcessStep;
import com.github.catchitcozucan.core.demo.test.support.io.IO;
import com.github.catchitcozucan.core.exception.ProcessRuntimeException;
import com.github.catchitcozucan.core.impl.ProcessBase;
import com.github.catchitcozucan.core.interfaces.PersistenceService;
import com.github.catchitcozucan.core.interfaces.ProcessSubject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.github.catchitcozucan.core.MakeStep;
import com.github.catchitcozucan.core.demo.trip.internal.BookingCentral;

@ProcessBpmSchemeRepo(relativePath = "../../../../../../resources/bpmSchemes")
public class TripProcess extends ProcessBase {

	private static final Logger LOGGER = LoggerFactory.getLogger(TripProcess.class);

	public static final TripStatus.Status[] CRITERIA_STATES = { TripStatus.Status.NEW_ORDER, TripStatus.Status.FLIGHT_NOT_CONFIRMED, TripStatus.Status.HOTEL_NOT_CONFIRMED, TripStatus.Status.CAR_NOT_CONFIRMED };

	protected TripProcess(ProcessSubject processSubject, PersistenceService persistenceService) {
		super(processSubject, persistenceService);
	}

	@Override
	public String name() {
		return "Booking a trip";
	}

	@Override
	public Enum<?>[] criteriaStates() {
		return CRITERIA_STATES;
	}
	@Override
	public Enum<?> finishedState() {
		return TripStatus.Status.CAR_CONFIRMED;
	}

	@Override
	public void process() {
		TripStatus.Status currentStatus = (TripStatus.Status) getSubject().getCurrentStatus();
		switch (currentStatus) {
			case NEW_ORDER:
			case FLIGHT_NOT_CONFIRMED:
				executeStep(bookFlightStep);
				break;
			case FLIGHT_CONFIRMED:
			case HOTEL_NOT_CONFIRMED:
				executeStep(bookHotelStep);
				break;
			case HOTEL_CONFIRMED:
			case CAR_NOT_CONFIRMED:
				executeStep(bookCarStep);
				break;
			default:
				Throwable t = new ProcessRuntimeException(String.format("Got bad input : order %s which is in state %s [%s]", getSubject().id(), getSubject().getCurrentStatus().name(), currentStatusDescription()));
				LOGGER.error("err", t);
				throw (RuntimeException) t;
		}
	}

	@MakeStep(description = "bookFlight", statusUponSuccess = "Status.FLIGHT_CONFIRMED", statusUponFailure = "Status.FLIGHT_NOT_CONFIRMED", enumStateProvider = com.github.catchitcozucan.core.demo.trip.TripStatus.class, sourceEncoding = IO.DEF_ENCODING)
	private void bookFlight() {
		((TripSubject) getSubject()).setFlightConfirmation(BookingCentral.getFlightConfirmation());
	}

	@MakeStep(description = "bookHotel", statusUponSuccess = "Status.HOTEL_CONFIRMED", statusUponFailure = "Status.HOTEL_NOT_CONFIRMED", enumStateProvider = com.github.catchitcozucan.core.demo.trip.TripStatus.class, sourceEncoding = IO.DEF_ENCODING)
	private void bookHotel() {
		((TripSubject) getSubject()).setHotelConfirmation(BookingCentral.getHotelConfirmation());
	}

	@MakeStep(description = "bookCar", statusUponSuccess = "Status.CAR_CONFIRMED", statusUponFailure = "Status.CAR_NOT_CONFIRMED", enumStateProvider = com.github.catchitcozucan.core.demo.trip.TripStatus.class, sourceEncoding = IO.DEF_ENCODING)
	private void bookCar() {
		((TripSubject) getSubject()).setCarConfirmation(BookingCentral.getCarConfirmation());
	}
	
    ///////CHKSUM: 8F9E8FBEC174C8235DE8B7A92BD44CF2XXXXXXXX/////////////////////
    //
    // The following code is generated by the DaProcessStepProcessor 
    // written by Ola Aronsson in 2020, courtesy of nollettnoll AB
    //
    // DO NOT edit this section. Modify @MakeStep or CHKSUM (then keep length)  to re-generate.
    //

    private final ProcessStep bookHotelStep = new ProcessStep(){ 

        @Override
        public void execute() {
            bookHotel();
        }

        @Override
        public String processName() {
            return "TRIPPROCESS";
        }

        @Override
        public String description() {
            return "bookHotel";
        }

        @Override
        public Enum<?> statusUponSuccess() {
            return com.github.catchitcozucan.core.demo.trip.TripStatus.Status.HOTEL_CONFIRMED;
        }

        @Override
        public Enum<?> statusUponFailure() {
            return com.github.catchitcozucan.core.demo.trip.TripStatus.Status.HOTEL_NOT_CONFIRMED;
        }

    };

    private final ProcessStep bookCarStep = new ProcessStep(){ 

        @Override
        public void execute() {
            bookCar();
        }

        @Override
        public String processName() {
            return "TRIPPROCESS";
        }

        @Override
        public String description() {
            return "bookCar";
        }

        @Override
        public Enum<?> statusUponSuccess() {
            return com.github.catchitcozucan.core.demo.trip.TripStatus.Status.CAR_CONFIRMED;
        }

        @Override
        public Enum<?> statusUponFailure() {
            return com.github.catchitcozucan.core.demo.trip.TripStatus.Status.CAR_NOT_CONFIRMED;
        }

    };

    private final ProcessStep bookFlightStep = new ProcessStep(){ 

        @Override
        public void execute() {
            bookFlight();
        }

        @Override
        public String processName() {
            return "TRIPPROCESS";
        }

        @Override
        public String description() {
            return "bookFlight";
        }

        @Override
        public Enum<?> statusUponSuccess() {
            return com.github.catchitcozucan.core.demo.trip.TripStatus.Status.FLIGHT_CONFIRMED;
        }

        @Override
        public Enum<?> statusUponFailure() {
            return com.github.catchitcozucan.core.demo.trip.TripStatus.Status.FLIGHT_NOT_CONFIRMED;
        }

    };

    ///////////////////////////////////////////////////////////////////////////////
    //
    // End DaProcessStepProcessor generation
    //

}